### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by jwyndreee** [myalos/monodepth2nyu#2]
Dear author,

https://github.com/myalos/monodepth2nyu/blob/19bf44b1ec3d9fd58cb62e74bbc1718232136974/trainer.py#L99

I suspect the number 1 among the arguments should be changed to len(self.opt.scales), regarding compatibility.

Anyway, huge thanks for sharing your code!

I am trying to reproduce the results you have mentioned in https://github.com/SJTU-ViSYS/StructDepth/issues/9

**Comment by myalos** [comment]
You are right. I copied many code from StructDepth. StructDepth use only one scale to train. Thanks for the correction.
